notifications:
  slack: cuencafinance:Vb7c4Zn7YCpT0wGjOFDwYQUM

language: node_js
node_js:
  - "stable"
install:
  - npm install

cache: npm

script:
  - mocha test/test.js
after_success:
  - npm run coverage
  - npm run coveralls
